[package]
name = "tmptmpfs"
version = "0.1.0"
authors = ["Nat Tuck <nat@ferrus.net>"]
edition = "2018"

[dependencies]
clap = { version = "~4.0.0", features = ["cargo", "wrap_help"] }
dirs = "~2.0.0"
json = "~0.11.0"
libc = "~0.2.0"
